### ISSUE TITLE
群号发一下

### ISSUE THREAD

**Issue by fengx1a0** [Hobr/Bilibili_show_ticket_order#10]
GitHub上相关项目还挺少的，主要是疫情结束之后的报复性消费和宅久了全出来逛导致出现了往年根本不会有的现象，再加上某角网络搞得一人一证一脸让人叹为观止的操作我觉得还是很有必要大搞特搞一下的

**Comment by fengx1a0** [comment]
我刚上岸的同学让我发条评论说大佬带带我们QwQ~

**Comment by Hobr** [comment]
我这只在抢cp29票时搞过一个群 818884376, ~里面没几个搞技术的~
