### ISSUE TITLE
大佬我想问下在开售前

### ISSUE THREAD

**Issue by axiliya2568** [Hobr/Bilibili_show_ticket_order#11]
再开售前怎么用api获得每个场次对应的token啊，就是不包括时间戳的

**Comment by Hobr** [comment]
开售前拿不到token(至少我没有研究出方法)

**Comment by axiliya2568** [comment]
大佬那就像是cp29捡漏也要先进去一次获得token才能捡漏吗，我看您主页的那个cp29在控制台输入代码获得token的是不是也要先进去一次支付页面才行

**Comment by Hobr** [comment]
> 大佬那就像是cp29捡漏也要先进去一次获得token才能捡漏吗，我看您主页的那个cp29在控制台输入代码获得token的是不是也要先进去一次支付页面才行

那个token也是在开售后得到的, b站后端写的开售后才能拿token, 不过也没有人研究过其他拿token的方法, 也许有办法
