### ISSUE TITLE
接口风控(Status code:412)

### ISSUE THREAD

**Issue by Hobr** [Hobr/Bilibili_show_ticket_order#2]
我以前没做过这方面，有没有搞过爬虫之类东西的大佬提一下解决方法
目前能做的也就是增加proxy切换功能或者增加请求时间间隔了。。

https://github.com/Hobr/cp_deprecate/issues/18
https://github.com/Hobr/cp_deprecate/issues/24

## 返回
错误号:412
由于触发哔哩哔哩安全风控策略，该次访问请求被拒绝。
The request was rejected because of the bilibili security control policy.

**Comment by Moss-001** [comment]
老兄，知道咋回事不，我在请求别的网站也有类似的情况

**Comment by Hobr** [comment]
> 老兄，知道咋回事不，我在请求别的网站也有类似的情况

就是服务端检测到异常行为的风控措施, B站是请求几个高危API过于频繁就封ip, 解决的话要么加sleep要么加ip池

**Comment by Moss-001** [comment]
嗯，我解决好了，一开始就是请求不行，浏览器还是可以访问，后来我检查cookie，修改了几个参数后就正常了。
