### ISSUE TITLE
[求助][Init]

### ISSUE THREAD

**Issue by Brown05** [Hobr/Bilibili_show_ticket_order#8]
我是命令行部署的，前面三条都没问题
不知道为什么我自己认为是卡在了venv这里
运行python init.py后给的是空反馈

**Comment by Brown05** [comment]
我自己这么认为的原因是我跑https://github.com/akaimoe/BilibiliTicketRushBuy 这个兄弟的项目是能跑的，但我目前需求的是你的项目的浏览器模式，想蹲回流票qwq

**Comment by Brown05** [comment]
还有一个问题就是 支持抢多个人的票吗 就是一张订单里面带上别人

**Comment by Hobr** [comment]
你可以试试这个[Hobr/cp_deprecate](https://github.com/Hobr/cp_deprecate), 现在这个repo是画的新饼, 但是我最近一直在考试, 所以这个repo啥都没写

**Comment by Brown05** [comment]
https://show.bilibili.com/platform/detail.html?id=68575
我好像没找到这个的场次token

**Comment by Hobr** [comment]
> https://show.bilibili.com/platform/detail.html?id=68575 我好像没找到这个的场次token

token只能在开售后获取
